# -*- coding: utf-8 -*-
"""array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTgACMVZJFW_-eVTQeRyd_9wj3vroM_9
"""

threeD_array = np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])
print(threeD_array)
print(threeD_array.shape)

import numpy as np
type(arr)
np.ndarray
arr.shape

arr2 = np.array([[1,2],[3,4]])
print(arr2)

threeD_array = np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])
print(threeD_array)
print(threeD_array.shape)