# -*- coding: utf-8 -*-
"""gender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1368dhvLeG3kzGtrenvYAlQhoupPsLqWd
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("gender_classification.csv")

df

print("Missing values:\n",df.isnull().sum())

print("\nDuplicate rows:",df.duplicated().sum())

df=df.drop_duplicates()

print("\nDuplicate rows:",df.duplicated().sum())

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
df["gender"]=le.fit_transform(df["gender"])

X=df.drop("gender",axis=1)
y=df["gender"]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

from sklearn.linear_model import LogisticRegression

log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

from sklearn.metrics import accuracy_score, classification_report
y_pred_log=log_reg.predict(X_test)
print("\nLogistic Regression Results")
print("Accuracy:",accuracy_score(y-test,y_pred_log))
print(classification _report (y_test,y_pred_log,target_names=["Female","Male"]))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
cm=confusion_matrix(y_test,y_pred_log)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=["Female","Male"])
disp.plot()
plt.title("Confusion Matrix-Logistic Regression")
plt.show()

new_data=[[0,13.5,6.2,1,1,0,1]]
new_data_df=pd.D