# -*- coding: utf-8 -*-
"""pycode1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lN0WXMuYYqJ2VKRamA0CpemTPbUNXMqt
"""

list=[]
list.append(1)
list.append(2)
list.append(4)
list.append(5)
list.append(6)
print("New list after append:",list)

list.insert(2,3)
print("list after insert:",list)

lst = [10, 20, 30]
new_list = [40, 50, 60]
lst.extend(new_list)
print("After extend:", lst)

lst1 = [10, 20, 30]
lst2 = [40, 50]
lst1.append(lst2)
print("Using append:", lst1)
lst1 = [10, 20, 30]
lst1.extend(lst2)
print("Using extend:", lst1)

lst = [10, 20, 30, 20, 40]
lst.remove(20)
print("After remove:", lst)

lst = [10, 20, 30, 40]
removed = lst.pop()
print("Removed:", removed)
print("List now:", lst)

lst = [10, 20, 30, 40, 50]
removed = lst.pop(3)
print("Removed element:", removed)
print("List now:", lst)

lst = [10, 20, 30]
lst.clear()
print("After clear:", lst)

lst = [10, 20, 30, 20, 40, 20]
count = lst.count(20)
print("Count of 20:", count)

lst = [10, 20, 30, 40]
index = lst.index(30)
print("Index of 30:", index)

lst = [10, 20, 30]
print(lst.index(50))

lst = [50, 10, 40, 20, 30]
lst.sort()
print("Ascending:", lst)