# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9_Qiv0nucK3T_RFOopMwNJavz5v9wzx
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("titanic.csv")

df

df.head()

df.shape

df.info()

df.duplicated().value_counts()

print(df.isnull().sum())

missing=df.isnull().sum()

ax=missing.plot(kind='bar',color='violet')
plt.title('Missing values per column')
plt.ylabel('Count of missing values')
plt.xlabel('column')
plt.xticks(rotation=45)

for index,value in enumerate(missing):
  plt.text(index,value+5,str(value),ha='center',va='bottom',fontsize=10,fontweight='bold')
  plt.tight_layout()
  plt.show()