# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOdpT485ZPULohl7L--7nWTybw_GXY0M
"""

lst1 = [10, 20]
lst2 = [30, 40]
lst1.extend(lst2)
print("Combined list:", lst1)