# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWMBEmYpjda1SbzMnHL2ZPwNAHFT5aWP
"""

import pandas as pd
data = {"Name": ["Asha", "Rahul", "Neha"],"Marks": [85, 90, 78]}
df = pd.DataFrame(data)
print(df)