# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdlOm7OGIYoBxOHJxO6zz8w11eH9p5Ah
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("titanic.csv")

df



















