# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Sp2g8Xl3CCIqyHNMLBJv6zL7pVphaoS
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

from google.colab import files
uploaded = files.upload()

import io

file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))
df.shape

print(df.info())

print(df.describe())

print(df.isnull().sum())

X=df.drop("price_range",axis=1)
y=df["price_range"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
