# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-a1fB7Fck6Gyb0-YEBHFeyhYoNWbh4bl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from scipy.stats import mode

iris = load_iris()

X = iris.data
y = iris.target

print("Shape:", X.shape)

df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

df.head()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print("Shape after PCA:", X_pca.shape)

kmeans = KMeans(n_clusters=3, random_state=42)

kmeans.fit(X_pca)
y_kmeans = kmeans.labels_

labels = np.zeros_like(y_kmeans)

for i in range(3):
    mask = (y_kmeans == i)
    labels[mask] = mode(y[mask], keepdims=True)[0]

accuracy = accuracy_score(y, labels)

print("Accuracy:", accuracy)

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_kmeans, cmap='viridis')

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("K-Means Clustering with PCA (Iris Dataset)")

plt.show()

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)