# -*- coding: utf-8 -*-
"""work27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1HQZCWXzcye41DDpST1Ja7qu65sKrxD
"""

import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

housing=fetch_california_housing()
X=pd.DataFrame(housing.data,columns=housing.feature_names)
y=housing.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

from tensorflow.keras.layers import Input
from tensorflow.keras.models import Sequential

model = Sequential([
    Input(shape=(X_train_scaled.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1)
])

model.compile(optimizer=Adam(learning_rate=0.001),loss='mse',metrics=['mae'])

history=model.fit(X_train_scaled,y_train,validation_split=0.2,epochs=50,batch_size=32)

loss,mae=model.evaluate(X_test_scaled,y_test)
print(f"Test MAE:{mae}")

predictions=model.predict(X_test_scaled)
print("First 5 predictions:",predictions[:5])

comparison=pd.DataFrame({'Actual':y_test[:10],'Predicted':predictions[:10].flatten()})
print(comparison)

