# -*- coding: utf-8 -*-
"""work24.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5M13KJc6Ip8rSZyMx4ejyMUiuysa0vg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from scipy.stats import mode

iris = load_iris()

X = iris.data
y = iris.target

print("Dataset Shape:", X.shape)

df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

df.head()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print("Shape after PCA:", X_pca.shape)

wcss = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_pca)   # or use X_scaled
    wcss.append(kmeans.inertia_)

plt.plot(K_range, wcss, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)

kmeans.fit(X_pca)

y_kmeans = kmeans.labels_

print("Cluster Labels:\n", y_kmeans)

labels = np.zeros_like(y_kmeans)

for i in range(3):
    mask = (y_kmeans == i)
    labels[mask] = mode(y[mask], keepdims=True)[0]

accuracy = accuracy_score(y, labels)

print("Accuracy:", accuracy)

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_kmeans)

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("K-Means Clustering with PCA (Iris Dataset)")

plt.show()

