# -*- coding: utf-8 -*-
"""work 24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKZN6CqVctnM_4YphzEavO7Rhs7HyAW3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
from scipy.stats import mode

iris=load_iris()
x=iris.data
y=iris.target
print("Shape of dataset:",x.shape)

df=pd.DataFrame(x,columns=iris.feature_names)
df['target']=y
df.head()

scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
print(x_scaled[:5])

inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(x_scaled)
    inertia.append(kmeans.inertia_)

Kmeans=KMeans(n_clusters=3,random_state=42)
Kmeans.fit(x_scaled)

for i, val in enumerate(inertia, start=1):
    print(f"Number of clusters = {i}, Inertia = {val:.2f}")

y_Kmeans=Kmeans.labels_
print("Cluster Labels:\n",y_Kmeans)

labels=np.zeros_like(y_Kmeans)
for i in range(3):
  mask=(y_Kmeans==i)
  labels[mask]=mode(y[mask],keepdims=True)[0]
  accuracy=accuracy_score(y,labels)
  print("Accuracy:",accuracy)

inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10) # Added n_init to suppress warning
    kmeans.fit(x_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(6,4))
plt.plot(range(1, 11), inertia, marker='o')
plt.title("Elbow Method to find optimal clusters")
plt.xlabel("Number of clusters")
plt.ylabel("Inertia")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(x_scaled)

# Add cluster info to dataframe
df['Cluster'] = clusters
print(df.head())

from sklearn.decomposition import PCA
import seaborn as sns

pca = PCA(n_components=2)
X_pca = pca.fit_transform(x_scaled)

df['PCA1'] = X_pca[:,0]
df['PCA2'] = X_pca[:,1]

# Plot clusters
plt.figure(figsize=(7,5))
sns.scatterplot(x='PCA1', y='PCA2', hue='Cluster', data=df, palette='Set1')
plt.title("Iris Clusters Visualization")
plt.show()